### ISSUE TITLE
Improve textbook audio

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/vicav-app#45] opened 2021-09-15 13:51 UTC
Audio Working with caveats 
Implement more functions to control the audio? 
* Use custom controls instead of relying on (very different) audio controls of the different browsers? 
* Automatically stop a recording if another is started? They play simultaneously right now

**Comment by dasch124** [comment] 2021-11-24 12:10
fixed in production. NB This is a duplicate of [https://redmine.acdh.oeaw.ac.at/issues/19578](https://redmine.acdh.oeaw.ac.at/issues/19578)

**Closed by dasch124** 2021-11-24 12:10 UTC
